export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_ERROR = "GET_ALL_POSTS_ERROR";

export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
export const GET_ALL_COMMENTS_SUCCESS = "GET_ALL_COMMENTS_SUCCESS";
export const GET_ALL_COMMENTS_ERROR = "GET_ALL_COMMENTS_ERROR";

export const GET_ALL_COMMENTS_BY_POSTID = "GET_ALL_COMMENTS_BY_POSTID";
export const GET_ALL_COMMENTS_BY_POSTID_SUCCESS = "GET_ALL_COMMENTS_BY_POSTID_SUCCESS";
export const GET_ALL_COMMENTS_BY_POSTID_ERROR = "GET_ALL_COMMENTS_BY_POSTID_ERROR";
